name: SlotsManager
version: 0.1
author: rfsantos1996
main: com.jabyftw.slotsmng.SlotManager
description: Manage your slots
permissions:
  slotmanager.change:
    description: 'Permission to use /slotsmanager'
    default: op
commands:
   slotsmanager:
      description: This is the main command for slot managing.
      usage: /<command> <slots>